name: nSAVE

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  archivar:
    runs-on: ubuntu-latest

    steps:
      - name: Comprobar repo de nSAVE
        uses: actions/checkout@v3

      - name: nSAVE script
        run: |
          chmod +x ./src/nsave.sh
          ./src/nsave.sh
# FODSOFT(TM). Neo Fodere de Frutos. All rights reserved.
